"""empty message

Revision ID: a214698daef0
Revises: 41643561d30f
Create Date: 2022-01-04 15:39:19.578337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a214698daef0'
down_revision = '41643561d30f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('pwd', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'pwd')
    # ### end Alembic commands ###
