"""empty message

Revision ID: ae836db9f84e
Revises: d0c83146d662
Create Date: 2022-01-04 00:41:51.142689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae836db9f84e'
down_revision = 'd0c83146d662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenic', sa.Column('addtime', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_scenic_addtime'), 'scenic', ['addtime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenic_addtime'), table_name='scenic')
    op.drop_column('scenic', 'addtime')
    # ### end Alembic commands ###
