"""empty message

Revision ID: cdd37b08d785
Revises: 24a6bd3db985
Create Date: 2022-01-04 00:46:55.767773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cdd37b08d785'
down_revision = '24a6bd3db985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_area_addtime', table_name='area')
    op.drop_index('name', table_name='area')
    op.drop_table('area')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('addtime', mysql.DATETIME(), nullable=True),
    sa.Column('is_recommended', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('introduction', mysql.TEXT(), nullable=True),
    sa.CheckConstraint('(`is_recommended` in (0,1))', name='area_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'area', ['name'], unique=True)
    op.create_index('ix_area_addtime', 'area', ['addtime'], unique=False)
    # ### end Alembic commands ###
